services:
  stats-db:
    image: postgres:16.4-alpine
    container_name: stats-db
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Present423
    ports:
      - "5432:5432"
  stats-server:
    build:
      context: ./stats/stats-server
      dockerfile: Dockerfile
    container_name:
      stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Present423
